# Generated by Django 2.2 on 2019-04-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='readed',
            field=models.BooleanField(default=False),
        ),
    ]
