# Generated by Django 2.2 on 2019-04-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20190411_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='name',
            new_name='title',
        ),
    ]
