# Generated by Django 2.2 on 2019-04-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20190429_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='title',
            new_name='name',
        ),
    ]
